import pandas as pd
import numpy as np
from sklearn.metrics import f1_score, accuracy_score, hamming_loss, roc_auc_score, average_precision_score

def compute_avg_auc(labels: np.ndarray, preds: np.ndarray):
    """Compute AUROC and AUPRC per pathway, then average (macro style)."""
    n_pathways = labels.shape[1]
    aurocs, auprcs = [], []
    for i in range(n_pathways):
        y_true = labels[:, i]
        y_pred = preds[:, i]
        # Skip if a pathway has only one class present (undefined AUROC/AUPRC)
        if len(np.unique(y_true)) < 2:
            continue
        aurocs.append(roc_auc_score(y_true, y_pred))
        auprcs.append(average_precision_score(y_true, y_pred))
    return (np.mean(aurocs) if aurocs else 0.0,
            np.mean(auprcs) if auprcs else 0.0)


def compute_flatten_auc(labels: np.ndarray, preds: np.ndarray):
    """Flatten all sample–pathway pairs into one vector (micro style)."""
    y_true = labels.ravel()
    y_pred = preds.ravel()
    # Handle degenerate case where all labels are 0/1
    if len(np.unique(y_true)) < 2:
        return 0.0, 0.0
    auroc = roc_auc_score(y_true, y_pred)
    auprc = average_precision_score(y_true, y_pred)
    return auroc, auprc


def compute_avg_auc_binary(labels: np.ndarray, preds_binary: np.ndarray):
    """Compute AUROC and AUPRC per pathway using binary predictions, then average (macro style)."""
    n_pathways = labels.shape[1]
    aurocs, auprcs = [], []
    for i in range(n_pathways):
        y_true = labels[:, i]
        y_pred_binary = preds_binary[:, i]
        # Skip if a pathway has only one class present (undefined AUROC/AUPRC)
        if len(np.unique(y_true)) < 2:
            continue
        # For binary predictions, AUC is just the balanced accuracy
        # But we'll still use sklearn functions for consistency
        try:
            aurocs.append(roc_auc_score(y_true, y_pred_binary))
            auprcs.append(average_precision_score(y_true, y_pred_binary))
        except ValueError:
            # Skip pathways where AUC cannot be computed
            continue
    return (np.mean(aurocs) if aurocs else 0.0,
            np.mean(auprcs) if auprcs else 0.0)


def compute_flatten_auc_binary(labels: np.ndarray, preds_binary: np.ndarray):
    """Flatten all sample–pathway pairs into one vector using binary predictions (micro style)."""
    y_true = labels.ravel()
    y_pred_binary = preds_binary.ravel()
    # Handle degenerate case where all labels are 0/1
    if len(np.unique(y_true)) < 2:
        return 0.0, 0.0
    auroc = roc_auc_score(y_true, y_pred_binary)
    auprc = average_precision_score(y_true, y_pred_binary)
    return auroc, auprc


def calculate_metrics_from_predictions_csv(csv_path):
    """
    Calculate metrics from the predictions CSV file generated by the DDP evaluation script.
    """
    # Load the CSV with proper header
    df = pd.read_csv(csv_path)
    
    print(f"Loaded CSV with {len(df)} samples")
    print(f"Columns: {list(df.columns[:10])}...")  # Show first 10 columns
    
    # Extract pathway columns
    pathway_cols = [col for col in df.columns if col.startswith('pathway_')]
    
    # Determine number of pathways
    pathway_numbers = set()
    for col in pathway_cols:
        if '_true' in col:
            pathway_num = int(col.split('_')[1])
            pathway_numbers.add(pathway_num)
    
    num_pathways = len(pathway_numbers)
    print(f"Number of pathways: {num_pathways}")
    
    # Initialize arrays
    y_true = np.zeros((len(df), num_pathways))
    y_prob = np.zeros((len(df), num_pathways))
    y_pred_threshold = np.zeros((len(df), num_pathways))
    y_pred_topk = np.zeros((len(df), num_pathways))
    
    # Extract data for each pathway
    for pathway_idx in range(num_pathways):
        true_col = f'pathway_{pathway_idx}_true'
        prob_col = f'pathway_{pathway_idx}_prob'
        thresh_col = f'pathway_{pathway_idx}_pred_threshold'
        
        # Find topk column (could be top2, top3, etc.)
        topk_col = None
        for col in df.columns:
            if col.startswith(f'pathway_{pathway_idx}_pred_top'):
                topk_col = col
                break
        
        if true_col in df.columns:
            y_true[:, pathway_idx] = df[true_col].values
        if prob_col in df.columns:
            y_prob[:, pathway_idx] = df[prob_col].values
        if thresh_col in df.columns:
            y_pred_threshold[:, pathway_idx] = df[thresh_col].values
        if topk_col and topk_col in df.columns:
            y_pred_topk[:, pathway_idx] = df[topk_col].values
    
    # Convert to integers for predictions
    y_true = y_true.astype(int)
    y_pred_threshold = y_pred_threshold.astype(int)
    y_pred_topk = y_pred_topk.astype(int)
    
    print(f"Data shapes:")
    print(f"  y_true: {y_true.shape}")
    print(f"  y_prob: {y_prob.shape}")
    print(f"  y_pred_threshold: {y_pred_threshold.shape}")
    print(f"  y_pred_topk: {y_pred_topk.shape}")
    
    # Calculate statistics
    print(f"\nLabel distribution:")
    print(f"  Total positive labels: {np.sum(y_true)}")
    print(f"  Average labels per sample: {np.mean(np.sum(y_true, axis=1)):.2f}")
    print(f"  Samples with at least one label: {np.sum(np.sum(y_true, axis=1) > 0)}")
    
    # Calculate metrics for threshold-based predictions
    print("\n" + "="*60)
    print("THRESHOLD-BASED PREDICTIONS (≥0.5)")
    print("="*60)
    
    threshold_metrics = calculate_multilabel_metrics(y_true, y_pred_threshold, y_prob)
    print_metrics(threshold_metrics)
    
    # Calculate metrics for top-k predictions
    print("\n" + "="*60)
    print("TOP-K PREDICTIONS")
    print("="*60)
    
    topk_metrics = calculate_multilabel_metrics(y_true, y_pred_topk, y_prob)
    print_metrics(topk_metrics)
    
    return {
        'y_true': y_true,
        'y_prob': y_prob,
        'y_pred_threshold': y_pred_threshold,
        'y_pred_topk': y_pred_topk,
        'threshold_metrics': threshold_metrics,
        'topk_metrics': topk_metrics
    }


def calculate_multilabel_metrics(y_true, y_pred, y_prob):
    """Calculate comprehensive multilabel metrics"""
    metrics = {}
    
    # Basic multilabel metrics
    metrics['subset_accuracy'] = accuracy_score(y_true, y_pred)  # Exact match ratio
    metrics['hamming_loss'] = hamming_loss(y_true, y_pred)
    
    # Partial accuracy metrics (giving partial credit for overlaps)
    metrics['partial_accuracy'] = calculate_partial_accuracy(y_true, y_pred)
    metrics['jaccard_accuracy'] = calculate_jaccard_accuracy(y_true, y_pred)
    metrics['weighted_overlap_accuracy'] = calculate_weighted_overlap_accuracy(y_true, y_pred)
    
    # F1 scores
    metrics['micro_f1'] = f1_score(y_true, y_pred, average='micro', zero_division=0)
    metrics['macro_f1'] = f1_score(y_true, y_pred, average='macro', zero_division=0)
    metrics['weighted_f1'] = f1_score(y_true, y_pred, average='weighted', zero_division=0)
    
    # Per-class F1 scores
    per_class_f1 = f1_score(y_true, y_pred, average=None, zero_division=0)
    metrics['per_class_f1'] = per_class_f1
    
    # ROC AUC and AUPRC (if probabilities are available)
    if y_prob is not None and not np.all(y_prob == 0):
        try:
            # Original ROC AUC calculations using probabilities
            metrics['roc_auc_macro'] = roc_auc_score(y_true, y_prob, average='macro')
            metrics['roc_auc_micro'] = roc_auc_score(y_true, y_prob, average='micro')
            
            # AUC metrics using probability scores
            avg_auroc, avg_auprc = compute_avg_auc(y_true, y_prob)
            metrics['avg_auroc_prob'] = avg_auroc
            metrics['avg_auprc_prob'] = avg_auprc
            
            flatten_auroc, flatten_auprc = compute_flatten_auc(y_true, y_prob)
            metrics['flatten_auroc_prob'] = flatten_auroc
            metrics['flatten_auprc_prob'] = flatten_auprc
            
        except ValueError as e:
            print(f"Warning: Could not calculate probability-based AUC metrics: {e}")
            metrics['roc_auc_macro'] = np.nan
            metrics['roc_auc_micro'] = np.nan
            metrics['avg_auroc_prob'] = np.nan
            metrics['avg_auprc_prob'] = np.nan
            metrics['flatten_auroc_prob'] = np.nan
            metrics['flatten_auprc_prob'] = np.nan
    else:
        metrics['roc_auc_macro'] = np.nan
        metrics['roc_auc_micro'] = np.nan
        metrics['avg_auroc_prob'] = np.nan
        metrics['avg_auprc_prob'] = np.nan
        metrics['flatten_auroc_prob'] = np.nan
        metrics['flatten_auprc_prob'] = np.nan
    
    # AUC metrics using binary predictions (for comparison with text model)
    try:
        avg_auroc_bin, avg_auprc_bin = compute_avg_auc_binary(y_true, y_pred)
        metrics['avg_auroc_binary'] = avg_auroc_bin
        metrics['avg_auprc_binary'] = avg_auprc_bin
        
        flatten_auroc_bin, flatten_auprc_bin = compute_flatten_auc_binary(y_true, y_pred)
        metrics['flatten_auroc_binary'] = flatten_auroc_bin
        metrics['flatten_auprc_binary'] = flatten_auprc_bin
        
    except ValueError as e:
        print(f"Warning: Could not calculate binary-based AUC metrics: {e}")
        metrics['avg_auroc_binary'] = np.nan
        metrics['avg_auprc_binary'] = np.nan
        metrics['flatten_auroc_binary'] = np.nan
        metrics['flatten_auprc_binary'] = np.nan
    
    # Additional statistics
    metrics['total_predictions'] = np.sum(y_pred)
    metrics['total_true_labels'] = np.sum(y_true)
    metrics['avg_predictions_per_sample'] = np.mean(np.sum(y_pred, axis=1))
    metrics['avg_true_labels_per_sample'] = np.mean(np.sum(y_true, axis=1))
    
    return metrics


def calculate_partial_accuracy(y_true, y_pred):
    """
    Calculate partial accuracy that gives partial credit for overlaps.
    Score is the intersection over union (Jaccard index) averaged over all samples.
    """
    scores = []
    for i in range(len(y_true)):
        intersection = np.sum(y_true[i] & y_pred[i])
        union = np.sum(y_true[i] | y_pred[i])
        
        if union == 0:
            # If both true and pred are all zeros, perfect match
            scores.append(1.0)
        else:
            scores.append(intersection / union)
    
    return np.mean(scores)


def calculate_jaccard_accuracy(y_true, y_pred):
    """
    Calculate Jaccard similarity (same as partial_accuracy but more explicit name).
    """
    return calculate_partial_accuracy(y_true, y_pred)


def calculate_weighted_overlap_accuracy(y_true, y_pred):
    """
    Calculate weighted overlap accuracy that gives different weights based on
    the number of true labels in each sample.
    
    For samples with more true labels, partial matches get higher credit.
    """
    scores = []
    for i in range(len(y_true)):
        true_count = np.sum(y_true[i])
        pred_count = np.sum(y_pred[i])
        intersection = np.sum(y_true[i] & y_pred[i])
        
        if true_count == 0 and pred_count == 0:
            # Perfect match when both are empty
            scores.append(1.0)
        elif true_count == 0:
            # True is empty but prediction is not - no credit
            scores.append(0.0)
        else:
            # Weighted score based on how many true labels were found
            recall_score = intersection / true_count
            precision_score = intersection / pred_count if pred_count > 0 else 0
            
            # Use F1-like combination of precision and recall
            if precision_score + recall_score > 0:
                f1_score = 2 * (precision_score * recall_score) / (precision_score + recall_score)
                scores.append(f1_score)
            else:
                scores.append(0.0)
    
    return np.mean(scores)


def calculate_k_accuracy(y_true, y_pred, k=1):
    """
    Calculate k-accuracy: percentage of samples where at least k true labels 
    are correctly predicted.
    """
    correct_samples = 0
    for i in range(len(y_true)):
        intersection = np.sum(y_true[i] & y_pred[i])
        if intersection >= k:
            correct_samples += 1
    
    return correct_samples / len(y_true)


def print_metrics(metrics):
    """Print metrics in a formatted way"""
    print(f"Subset Accuracy (Exact Match): {metrics['subset_accuracy']:.4f}")
    print(f"Hamming Loss: {metrics['hamming_loss']:.4f}")
    print(f"Partial Accuracy (Jaccard): {metrics['partial_accuracy']:.4f}")
    print(f"Jaccard Accuracy: {metrics['jaccard_accuracy']:.4f}")
    print(f"Weighted Overlap Accuracy: {metrics['weighted_overlap_accuracy']:.4f}")
    print(f"Micro F1: {metrics['micro_f1']:.4f}")
    print(f"Macro F1: {metrics['macro_f1']:.4f}")
    print(f"Weighted F1: {metrics['weighted_f1']:.4f}")
    
    # AUC metrics (if available)
    if not np.isnan(metrics['roc_auc_macro']):
        print(f"ROC AUC (Macro): {metrics['roc_auc_macro']:.4f}")
        print(f"ROC AUC (Micro): {metrics['roc_auc_micro']:.4f}")
    
    # Probability-based AUC metrics
    if not np.isnan(metrics['avg_auroc_prob']):
        print(f"Avg AUROC (per-pathway, prob): {metrics['avg_auroc_prob']:.4f}")
        print(f"Avg AUPRC (per-pathway, prob): {metrics['avg_auprc_prob']:.4f}")
        print(f"Flatten AUROC (micro-style, prob): {metrics['flatten_auroc_prob']:.4f}")
        print(f"Flatten AUPRC (micro-style, prob): {metrics['flatten_auprc_prob']:.4f}")
    
    # Binary-based AUC metrics (for comparison with text model)
    if not np.isnan(metrics['avg_auroc_binary']):
        print(f"Avg AUROC (per-pathway, binary): {metrics['avg_auroc_binary']:.4f}")
        print(f"Avg AUPRC (per-pathway, binary): {metrics['avg_auprc_binary']:.4f}")
        print(f"Flatten AUROC (micro-style, binary): {metrics['flatten_auroc_binary']:.4f}")
        print(f"Flatten AUPRC (micro-style, binary): {metrics['flatten_auprc_binary']:.4f}")
    
    print(f"\nPrediction Statistics:")
    print(f"  Total predictions made: {int(metrics['total_predictions'])}")
    print(f"  Total true labels: {int(metrics['total_true_labels'])}")
    print(f"  Avg predictions per sample: {metrics['avg_predictions_per_sample']:.2f}")
    print(f"  Avg true labels per sample: {metrics['avg_true_labels_per_sample']:.2f}")
    
    # Show per-class F1 statistics
    per_class_f1 = metrics['per_class_f1']
    print(f"\nPer-class F1 Statistics:")
    print(f"  Mean: {np.mean(per_class_f1):.4f}")
    print(f"  Std: {np.std(per_class_f1):.4f}")
    print(f"  Min: {np.min(per_class_f1):.4f}")
    print(f"  Max: {np.max(per_class_f1):.4f}")
    print(f"  Classes with F1=0: {np.sum(per_class_f1 == 0)}")


def analyze_predictions_detailed(y_true, y_pred, pathway_names=None):
    """Provide detailed analysis of predictions"""
    print("\n" + "="*60)
    print("DETAILED PREDICTION ANALYSIS")
    print("="*60)
    
    num_samples, num_pathways = y_true.shape
    
    # Per-pathway analysis
    print(f"\nPer-pathway analysis:")
    print("-" * 40)
    
    for i in range(min(num_pathways, 10)):  # Show first 10 pathways
        pathway_name = f"Pathway {i}" if pathway_names is None else pathway_names[i]
        
        true_pos = np.sum((y_true[:, i] == 1) & (y_pred[:, i] == 1))
        false_pos = np.sum((y_true[:, i] == 0) & (y_pred[:, i] == 1))
        false_neg = np.sum((y_true[:, i] == 1) & (y_pred[:, i] == 0))
        true_neg = np.sum((y_true[:, i] == 0) & (y_pred[:, i] == 0))
        
        precision = true_pos / (true_pos + false_pos) if (true_pos + false_pos) > 0 else 0
        recall = true_pos / (true_pos + false_neg) if (true_pos + false_neg) > 0 else 0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
        
        print(f"{pathway_name}: TP={true_pos}, FP={false_pos}, FN={false_neg}, "
              f"P={precision:.3f}, R={recall:.3f}, F1={f1:.3f}")
    
    if num_pathways > 10:
        print(f"... and {num_pathways - 10} more pathways")


# Main execution
if __name__ == "__main__":
    # Update this path to your actual CSV file
    csv_path = "/home/arism/test_results_ddp/predictions.csv"
    
    try:
        results = calculate_metrics_from_predictions_csv(csv_path)
        
        # Perform detailed analysis
        analyze_predictions_detailed(
            results['y_true'], 
            results['y_pred_threshold']
        )
        
        # Calculate additional k-accuracy metrics
        print("\n" + "="*60)
        print("K-ACCURACY ANALYSIS")
        print("="*60)
        
        for k in [1, 2, 3]:
            k_acc_thresh = calculate_k_accuracy(results['y_true'], results['y_pred_threshold'], k=k)
            k_acc_topk = calculate_k_accuracy(results['y_true'], results['y_pred_topk'], k=k)
            print(f"At least {k} correct (Threshold): {k_acc_thresh:.4f}")
            print(f"At least {k} correct (Top-k): {k_acc_topk:.4f}")
        
        print("\n" + "="*60)
        print("ANALYSIS COMPLETE")
        print("="*60)
        
    except Exception as e:
        print(f"Error: {e}")
        print("\nPlease check that:")
        print("1. The CSV file path is correct")
        print("2. The CSV file has the expected format with pathway columns")
        print("3. The file is not corrupted or empty")