model:
  geneformer_model_path: "/home/arism/cell2text/Geneformer/"
  freeze_geneformer: true
  
data:
  base_data_path: "/home/arism/datasets/zip_dataset"
  
training:
  learning_rate: 1e-4
  batch_size: 256
  num_epochs: 2
  gradient_accumulation_steps: 1
  k_pathways: 2
  device: "cuda"
  
